# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bef4bb1d726244e51d7b43826012b9949be43c5c6a3533c1da664648a51979acda5a08bed282cf31c3a20254124ef7efd02d03a823083d274a7291c21307367

test:
  secret_key_base: c545424f4674b9044130602acd254f7b3f2f09314de5d32c8ee76c8134516cd4e15637e6c8e8b56665bb1c78a409dade5dc3e06cba5066d1412d54821d6c38fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
